# Generated by Django 4.1.1 on 2022-10-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='test',
            new_name='text',
        ),
    ]
