# Generated by Django 4.1.1 on 2022-12-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restelements',
            old_name='done',
            new_name='sent',
        ),
    ]
